//error4.cpp Ц использование классов исключений
#include <iostream>
#include <cmath> // или math.h, пользовател€м unix может потребоватьс€ флаг -lm
#include "exc_mean.h"
// прототипы функций
namespace ERROR4 {
	double hmean(double a, double b);
	double gmean(double a, double b);
}

int error4() {
    using std::cout;
    using std::cin;
    using std::endl;
    using namespace ERROR4;
    
    double x, y, z;

    cout << "Enter two numbers: ";
    while (cin >> x >> y) {
        try {                  // начало блока try
            z = hmean(x,y);
            cout << "Harmonic mean of " << x << " and " << y
                << " is " << z << endl;
            cout << "Geometric mean of " << x << " and " << y
                << " is " << gmean(x,y) << endl;
            cout << "Enter next set of numbers <q to quit>: ";
        }						// конец блока try
        catch (bad_hmean & bg) {   // начало блока try
            bg.mesg();
            cout << "Try again.\n";
            continue;
        }                  
        catch (bad_gmean & hg) {
            cout << hg.mesg();
            cout << "Values used: " << hg.v1 << ", " 
                 << hg.v2 << endl;
            cout << "Sorry, you don't get to play any more.\n";
            break;
        } // конец блока try
    }
    cout << "Bye!\n";
    // cin.get();
    // cin.get();
    return 0;
}

double ERROR4::hmean(double a, double b) {
    if (a == -b)
        throw bad_hmean(a, b);
    return 2.0 * a * b / (a + b);
}

double ERROR4::gmean(double a, double b) {
    if (a < 0 || b < 0)
        throw bad_gmean(a, b);
    return std::sqrt(a * b); 
}
